#!/bin/bash
# Basic for command

for test in Alabama Alaska Arizona Arkansas California Colorado
do
  echo "The next state is $test"
done

echo "The last state we visited was $test"
test=Conneticut
echo "Wait, now we're visited $test" 
