#!/bin/bash
# iterate through alll the files in a directory

for file in $HOME/Documents/*
do
  if [ -d "$file" ]
  then
    echo "$file is a directory"
  elif [ -f "$file" ]
  then
    echo "$file is a file"
  fi
done
